/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --env-interface CloudflareEnv --include-runtime false` (hash: 56950bedc376c82b6aaa87433d823e99)
declare namespace Cloudflare {
	interface Env {
		DB: D1Database;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
