/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as tabsIndexRouteImport } from './routes/(tabs)/index'
import { Route as tabsRankingIndexRouteImport } from './routes/(tabs)/ranking/index'
import { Route as tabsQuizIndexRouteImport } from './routes/(tabs)/quiz/index'
import { Route as tabsProfileIndexRouteImport } from './routes/(tabs)/profile/index'
import { Route as tabsQuizResultRouteImport } from './routes/(tabs)/quiz/result'
import { Route as tabsQuizQuestionRouteImport } from './routes/(tabs)/quiz/question'
import { Route as tabsQuizCreateRouteImport } from './routes/(tabs)/quiz/create'
import { Route as tabsQuizSessionIdRouteImport } from './routes/(tabs)/quiz/$sessionId'

const tabsIndexRoute = tabsIndexRouteImport.update({
  id: '/(tabs)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const tabsRankingIndexRoute = tabsRankingIndexRouteImport.update({
  id: '/(tabs)/ranking/',
  path: '/ranking/',
  getParentRoute: () => rootRouteImport,
} as any)
const tabsQuizIndexRoute = tabsQuizIndexRouteImport.update({
  id: '/(tabs)/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const tabsProfileIndexRoute = tabsProfileIndexRouteImport.update({
  id: '/(tabs)/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const tabsQuizResultRoute = tabsQuizResultRouteImport.update({
  id: '/(tabs)/quiz/result',
  path: '/quiz/result',
  getParentRoute: () => rootRouteImport,
} as any)
const tabsQuizQuestionRoute = tabsQuizQuestionRouteImport.update({
  id: '/(tabs)/quiz/question',
  path: '/quiz/question',
  getParentRoute: () => rootRouteImport,
} as any)
const tabsQuizCreateRoute = tabsQuizCreateRouteImport.update({
  id: '/(tabs)/quiz/create',
  path: '/quiz/create',
  getParentRoute: () => rootRouteImport,
} as any)
const tabsQuizSessionIdRoute = tabsQuizSessionIdRouteImport.update({
  id: '/(tabs)/quiz/$sessionId',
  path: '/quiz/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof tabsIndexRoute
  '/quiz/$sessionId': typeof tabsQuizSessionIdRoute
  '/quiz/create': typeof tabsQuizCreateRoute
  '/quiz/question': typeof tabsQuizQuestionRoute
  '/quiz/result': typeof tabsQuizResultRoute
  '/profile/': typeof tabsProfileIndexRoute
  '/quiz/': typeof tabsQuizIndexRoute
  '/ranking/': typeof tabsRankingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof tabsIndexRoute
  '/quiz/$sessionId': typeof tabsQuizSessionIdRoute
  '/quiz/create': typeof tabsQuizCreateRoute
  '/quiz/question': typeof tabsQuizQuestionRoute
  '/quiz/result': typeof tabsQuizResultRoute
  '/profile': typeof tabsProfileIndexRoute
  '/quiz': typeof tabsQuizIndexRoute
  '/ranking': typeof tabsRankingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(tabs)/': typeof tabsIndexRoute
  '/(tabs)/quiz/$sessionId': typeof tabsQuizSessionIdRoute
  '/(tabs)/quiz/create': typeof tabsQuizCreateRoute
  '/(tabs)/quiz/question': typeof tabsQuizQuestionRoute
  '/(tabs)/quiz/result': typeof tabsQuizResultRoute
  '/(tabs)/profile/': typeof tabsProfileIndexRoute
  '/(tabs)/quiz/': typeof tabsQuizIndexRoute
  '/(tabs)/ranking/': typeof tabsRankingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/quiz/$sessionId'
    | '/quiz/create'
    | '/quiz/question'
    | '/quiz/result'
    | '/profile/'
    | '/quiz/'
    | '/ranking/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/quiz/$sessionId'
    | '/quiz/create'
    | '/quiz/question'
    | '/quiz/result'
    | '/profile'
    | '/quiz'
    | '/ranking'
  id:
    | '__root__'
    | '/(tabs)/'
    | '/(tabs)/quiz/$sessionId'
    | '/(tabs)/quiz/create'
    | '/(tabs)/quiz/question'
    | '/(tabs)/quiz/result'
    | '/(tabs)/profile/'
    | '/(tabs)/quiz/'
    | '/(tabs)/ranking/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  tabsIndexRoute: typeof tabsIndexRoute
  tabsQuizSessionIdRoute: typeof tabsQuizSessionIdRoute
  tabsQuizCreateRoute: typeof tabsQuizCreateRoute
  tabsQuizQuestionRoute: typeof tabsQuizQuestionRoute
  tabsQuizResultRoute: typeof tabsQuizResultRoute
  tabsProfileIndexRoute: typeof tabsProfileIndexRoute
  tabsQuizIndexRoute: typeof tabsQuizIndexRoute
  tabsRankingIndexRoute: typeof tabsRankingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(tabs)/': {
      id: '/(tabs)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof tabsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tabs)/ranking/': {
      id: '/(tabs)/ranking/'
      path: '/ranking'
      fullPath: '/ranking/'
      preLoaderRoute: typeof tabsRankingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tabs)/quiz/': {
      id: '/(tabs)/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof tabsQuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tabs)/profile/': {
      id: '/(tabs)/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof tabsProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tabs)/quiz/result': {
      id: '/(tabs)/quiz/result'
      path: '/quiz/result'
      fullPath: '/quiz/result'
      preLoaderRoute: typeof tabsQuizResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tabs)/quiz/question': {
      id: '/(tabs)/quiz/question'
      path: '/quiz/question'
      fullPath: '/quiz/question'
      preLoaderRoute: typeof tabsQuizQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tabs)/quiz/create': {
      id: '/(tabs)/quiz/create'
      path: '/quiz/create'
      fullPath: '/quiz/create'
      preLoaderRoute: typeof tabsQuizCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tabs)/quiz/$sessionId': {
      id: '/(tabs)/quiz/$sessionId'
      path: '/quiz/$sessionId'
      fullPath: '/quiz/$sessionId'
      preLoaderRoute: typeof tabsQuizSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  tabsIndexRoute: tabsIndexRoute,
  tabsQuizSessionIdRoute: tabsQuizSessionIdRoute,
  tabsQuizCreateRoute: tabsQuizCreateRoute,
  tabsQuizQuestionRoute: tabsQuizQuestionRoute,
  tabsQuizResultRoute: tabsQuizResultRoute,
  tabsProfileIndexRoute: tabsProfileIndexRoute,
  tabsQuizIndexRoute: tabsQuizIndexRoute,
  tabsRankingIndexRoute: tabsRankingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
